---
# tasks file for lighttpd
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install Lighttpd
  ansible.builtin.package:
    name: lighttpd
    state: present

- name: Ensure Lighttpd configuration file is present
  ansible.builtin.template:
    src: lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
    mode: "0644"
    owner: root
    group: root
  notify: Restart lighttpd

- name: Create Lighttpd user and group
  ansible.builtin.group:
    name: "{{ lighttpd_user }}"
    state: present

- name: Create Lighttpd user
  ansible.builtin.user:
    name: "{{ lighttpd_user }}"
    group: "{{ lighttpd_user }}"
    home: /var/www/html
    shell: /sbin/nologin
    state: present

- name: Set log directory permissions
  ansible.builtin.file:
    path: /var/log/lighttpd
    owner: "{{ lighttpd_user }}"
    group: "{{ lighttpd_user }}"
    mode: "0755"
    recurse: true

- name: Create temporary directory for Lighttpd
  ansible.builtin.file:
    path: /tmp/lighttpdcompress
    state: directory
    owner: "{{ lighttpd_user }}"
    group: "{{ lighttpd_user }}"
    mode: "0755"

- name: Create directory for Lighttpd service override
  ansible.builtin.file:
    path: /lib/systemd/system/lighttpd.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add run script on service startup
  ansible.builtin.copy:
    dest: /lib/systemd/system/lighttpd.service.d/override.conf
    content: |
      [Service]
      ExecStartPre=chown -R {{ lighttpd_user }}:{{ lighttpd_user }} /var/log/lighttpd
    owner: root
    group: root
    mode: "0644"
  notify: Restart lighttpd


- name: Clone website to local
  ansible.builtin.git:
    repo: "{{ lighttpd_git_source }}"
    dest: /var/www/html/{{ lighttpd_website_name }}
    single_branch: true
    version: main
    depth: 1
  notify: Restart lighttpd

- name: Ensure Lighttpd service is enabled and started
  ansible.builtin.systemd:
    name: lighttpd
    state: started
    enabled: true
