---
- name: Converge
  hosts: all

  roles:
    - role: TychoBrouwer.git
      git_name: Test Test
      git_email: test@test.com

    - role: lighttpd
      lighttpd_git_source: https://github.com/TychoBrouwer/personal-website-elm.git
      lighttpd_website_name: portfolio
      lighttpd_server_ip: 192.168.1.106
      lighttpd_server_address: https://mywebsite.com
      lighttpd_rules:
        - |
          url.rewrite-once = (
            "^/(dist|images|api)/(.*)$" =>      "/$1/$2",
            "^/robots.txt$"             =>      "/robots.txt",
            ".*"                        =>      "/"
          )
        - |
          url.redirect = (
            "^/(projects)$"             =>      "/index.html"
          )

  tasks:
    - name: Check if rules in config
      ansible.builtin.replace:
        path: /etc/lighttpd/lighttpd.conf
        regexp: "{{ item }}"
      check_mode: true
      register: block_exists
      failed_when: block_exists.changed
      with_items: "{{ lighttpd_rules }}"
