---
- name: Converge
  hosts: all

  roles:
    - role: TychoBrouwer.git
      role_git_name: Test Test
      role_git_email: test@test.com

    - role: lighttpd
      role_git_source: https://github.com/TychoBrouwer/personal-website-elm.git
      role_website_name: portfolio
      role_server_ip: 192.168.1.106
      role_server_address: https://mywebsite.com
      role_lighttpd_rules:
        - |
          url.rewrite-once = (
            "^/(dist|images|api)/(.*)$" =>      "/$1/$2",
            "^/robots.txt$"             =>      "/robots.txt",
            ".*"                        =>      "/"
          )
        - |
          url.redirect = (
            "^/(projects)$"             =>      "/index.html"
          )

  tasks:
    - name: Check if rules in config
      replace:
        path: /etc/lighttpd/lighttpd.conf
        regexp: "{{ item }}"
      check_mode: yes
      register: block_exists
      failed_when: block_exists.changed
      with_items: role_lighttpd_rules
